

"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect, useState  } from "react";
import Script from "next/script";
import { usePathname } from "next/navigation";
import dynamic from "next/dynamic";
import Header from "./cutomer_component/Header";
import Footer from "./cutomer_component/Footer";
// import Footer from "../(front)/frontComponents/Footer";
// Footer






const jQuery = dynamic(() => import('jquery'), { ssr: false });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  
  

  return (
    <html lang="en">
      
      <meta charSet="UTF-8" />
      <meta name="description" content="" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="keywords" content="" />
      <title>Sellora</title>
      <link rel="shortcut icon" href="/front/favicon.ico" type="image/x-icon" />
    
      <link rel="stylesheet preload" href="/front/assets/css/plugins.css" as="style" />
      <link rel="stylesheet preload" href="/front/assets/css/style.css" as="style" />
      <body className="index-five">
        {/* <Header />
        {children}
        <Footer/> */}

        <Header />
        {children}
         <Footer />
   

   
         <Script defer src="/front/assets/js/plugins.js"></Script>
    <Script defer src="/front/assets/js/main.js"></Script>
    <Script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></Script>
    <Script src="/front/assets/js/jquery.min.js"></Script>




      </body>
    </html>
  );
}
